name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave selenium webdriver-manager pytest pyhamcrest allure-behave

      - name: Run tests and generate Allure report
        run: |
          mkdir -p features/reports
          behave -f allure_behave.formatter:AllureFormatter -o features/reports

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: features/reports
          retention-days: 5

      - name: Generate Allure Report
        run: |
          allure generate features/reports -o features/allure-report --clean

      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-html-report
          path: features/allure-report
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-html-report
          path: features/allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./features/allure-report
