name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker_build_and_publish_reports:
    runs-on: ubuntu-latest
    needs: test_execution

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Docker image from the Dockerfile
      - name: Build Docker image
        run: docker build -t ci-pipeline .

      # Run tests inside the Docker container and export it to results in same folder 
      - name: Run tests inside Docker container
        run: |
          docker run -v $(pwd)/features/reports:/app/features/reports ci-pipeline

  environment_setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo apt-get --only-upgrade install google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave selenium webdriver-manager pytest pyhamcrest allure-behave allure-python-commons

      - name: Install Allure CLI manually
        run: |
          # Download Allure CLI
          wget https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz
          # Extract the archive
          tar -zxvf allure-2.20.1.tgz
          # Move allure to /usr/bin
          sudo mv allure-2.20.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Create directories for Allure results and history
        run: |
          mkdir -p features/reports/allure-results/history

      # Step to retrieve previous Allure history from a branch
      - name: Download Allure history from branch
        run: |
          git fetch origin allure-history-branch
          git checkout origin/allure-history-branch -- features/reports/allure-results/history || echo "No previous history found"

      - name: Run tests and generate Allure results
        run: |
          mkdir -p features/reports/allure-results
          behave -f allure_behave.formatter:AllureFormatter -o features/reports/allure-results || true
          
      - name: Merge previous Allure history
        run: |
          cp -R features/reports/allure-results/history/* features/reports/allure-results/ || echo "No previous history to merge"

      - name: Generate Allure Report
        run: |
          allure generate features/reports/allure-results -o features/allure-report --clean

      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-html-report
          path: features/allure-report
          retention-days: 5

      - name: Handle untracked files (move to temp)
        run: |
          mkdir -p temp
          mv features/allure-report/* temp/ || echo "No files to move"

      - name: Commit and push Allure history to branch
        run: |
          git config pull.rebase false
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          
          # Add all changes or stash untracked ones
          git add --all || git stash

          # Fetch the latest history branch
          git fetch origin allure-history-branch

          # Checkout the history branch
          git checkout allure-history-branch || git checkout -b allure-history-branch

          # Pull changes and merge allowing unrelated histories
          git pull origin allure-history-branch --no-edit --allow-unrelated-histories || echo "No changes to pull"

          # Add the directories to track history and reports
          git add features/reports/ features/allure-report/ features/reports/allure-results/

          # Commit the changes if any
          git commit -m "Update Allure history and report" || echo "No changes to commit"

          # Push changes back to the branch with force to ensure sync
          git push origin allure-history-branch --force

  test_execution:
    runs-on: ubuntu-latest
    needs: environment_setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-html-report
          path: features/allure-report

      - name: Deploy Allure report to a separate branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./features/allure-report
          publish_branch: main
          force_orphan: true
